spring:
  datasource:
    url: jdbc:postgresql://ep-dawn-water-ao9y3w3k-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_yroJGfD3nxi5&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_yroJGfD3nxi5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:equisplit-development-secret-key-change-before-production-123456789}
  expiration: 86400000